language: cpp
sudo:     required

services:
    - docker

cache:
  ccache: true
  directories:
    - $HOME/build-cache

matrix:
  include:
    - compiler: clang
      env: TOOL=scons CXXSTD=11 NLS=true LTS=1604 BRANCH=1.14

    - compiler: gcc
      env: TOOL=scons CXXSTD=14 NLS=false LTS=1604 BRANCH=1.14

    - compiler: gcc
      env: TOOL=scons CXXSTD=11 NLS=false LTS=1604 BRANCH=1.14 OPT=-O0

    - compiler: gcc
      env: TOOL=cmake CXXSTD=11 NLS=false LTS=1604 BRANCH=1.14

    - compiler: clang
      env: TOOL=scons CXXSTD=11 NLS=false LTS=1604 BRANCH=1.14 OPT=-O0

    - compiler: clang
      env: TOOL=cmake CXXSTD=11 NLS=false LTS=1604 BRANCH=1.14

    - os: osx
      compiler: clang
      env: TOOL=scons CXXSTD=11 NLS=false OPT=-O0

    - os: osx
      compiler: clang
      env: TOOL=xcodebuild

install:
    - . ./utils/travis/steps/install.sh

script:
    - ./utils/travis/steps/script.sh

notifications:
    email: false
    irc:
        channels:
# "chat.freenode.net#wesnoth-dev"
            - secure: "HwCgH1VmpYbfv4giKIGkATkWc6o1+HXH827JXwxDnwFGZrLyf+1t4mHC6OaTMOFkZvT7qhSfIe80GeiRkg2x14ZpUE9XYewUUOSq7dRJlk2KLWlGRf5fZFHZVEdDOPdTdJjCLGqddY+4sMjqMlrtgIOxbPSXKLPTJLBhEEr8ZqE="
        template:
            - "\x02%{repository}\x0f#\x0312%{build_number}\x0f (\x0307%{branch}\x0f - \x02%{commit}\x0f : \x0303%{author}\x0f): \x02%{message}\x0f"
            - "Build details : \x0302%{build_url}\x0f"
        on_success: change
        on_failure: always
